/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

synchronized public void drawDuringGameWindow(PApplet appc, GWinData data) { //_CODE_:duringGameWindow:769630:
  appc.background(230);
  //appc.background(guiBackground); // has to have the same size as application
  // IDEA: maybe have bunch of "theme" photos that everyGUI has?
} //_CODE_:duringGameWindow:769630:

public void powerButtonClicked(GButton source, GEvent event) { //_CODE_:powerButton:594449:
  powerUsed = true;
} //_CODE_:powerButton:594449:

public void agroSliderChanged(GCustomSlider source, GEvent event) { //_CODE_:aggroSlider:296709:
  aggressiveness = aggroSlider.getValueF();
} //_CODE_:aggroSlider:296709:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  duringGameWindow = GWindow.getWindow(this, "Window title", 0, 0, 400, 120, JAVA2D);
  duringGameWindow.noLoop();
  duringGameWindow.setActionOnClose(G4P.CLOSE_WINDOW);
  duringGameWindow.addDrawHandler(this, "drawDuringGameWindow");
  powerButton = new GButton(duringGameWindow, 120, 80, 80, 30);
  powerButton.setText("POWER");
  powerButton.setLocalColorScheme(GCScheme.GOLD_SCHEME);
  powerButton.addEventHandler(this, "powerButtonClicked");
  aggroLabel = new GLabel(duringGameWindow, 10, 30, 110, 30);
  aggroLabel.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  aggroLabel.setText("Aggressiveness");
  aggroLabel.setLocalColorScheme(GCScheme.GOLD_SCHEME);
  aggroLabel.setOpaque(false);
  aggroSlider = new GCustomSlider(duringGameWindow, 152, 12, 220, 60, "grey_blue");
  aggroSlider.setShowLimits(true);
  aggroSlider.setLimits(0.5, 0.0, 1.0);
  aggroSlider.setNbrTicks(11);
  aggroSlider.setStickToTicks(true);
  aggroSlider.setShowTicks(true);
  aggroSlider.setNumberFormat(G4P.DECIMAL, 2);
  aggroSlider.setLocalColorScheme(GCScheme.GOLD_SCHEME);
  aggroSlider.setOpaque(false);
  aggroSlider.addEventHandler(this, "agroSliderChanged");
  duringGameWindow.loop();
}

// Variable declarations 
// autogenerated do not edit
GWindow duringGameWindow;
GButton powerButton; 
GLabel aggroLabel; 
GCustomSlider aggroSlider; 
